#ifndef CONST_H_INCLUDED
#define CONST_H_INCLUDED

#define WINDOWS_WIDTH 1024
#define WINDOWS_HEIGHT 720

#define BALL_SIZE 20
#define BALL_SPEED 5

#define PLAYER_WIDTH 14
#define PLAYER_HEIGHT 60
#define PLAYER_SPEED 10
#define PLAYER_Y 120

#define PLAYER1_X PLAYER_WIDTH-5
#define PLAYER2_X WINDOWS_WIDTH-PLAYER_WIDTH-5

#define SCORE_MAX 5

#endif // CONST_H_INCLUDED
